services:
  db:
    image: postgres:16
    env_file:
      - configs/.env.dev
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/db_data
    healthcheck:
      test: "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6389:6379'
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  db_migrations:
    build:
      context: .
    #env_file:
    #  - configs/.env.dev
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      DB_HOST: db
      DB_PORT: 5432
    command: sh migrate.sh
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: